quarkus:
  application:
    name: simple-ping-pong-server
  http:
    port: 8085

  grpc:
    clients:
      pingPong:
        host: localhost
    server:
      port: 9999

  jib:
    base-jvm-image: registry.access.redhat.com/ubi9/openjdk-17-runtime:1.14
    jvm-entrypoint: /entrypoint.sh
    working-directory: /work