kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.front.name }}
  labels:
    {{- include "ping-pong.labels" . | nindent 4 }}
spec:
  type: {{ .Values.front.service.type }}
  ports:
    - port: {{ .Values.front.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: ping-pong-front